baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'test'
theme = 'hugo-book'
sectionPagesMenu = 'main'
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true